strings:
  inputs:
    - Resources/en.lproj/Localizable.strings
  outputs:
    - templateName: structured-swift5
      output: Packages/Shared/Sources/Shared/Resources/Generated/Localizable.swift
      params:
        publicAccess: true
