strings:
  inputs:
    - Resources/en.lproj/Localizable.strings
  outputs:
    - templateName: structured-swift5
      output: TopLevel/Sources/TopLevel/Generated/Localizable.swift
      params:
        publicAccess: true
